2024-05-11 16:21:09,625 : INFO : root : Loading config.
2024-05-11 16:21:09,627 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-05-11 16:21:09,627 : INFO : ConfigProcessor : Loading config from cache: C:\Users\octo\AppData\Local\Temp\1d0904511285da59b68333680e0b91d2.mpf_cache
2024-05-11 16:21:09,631 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\octo\Downloads\homebrew\config\coils.yaml
2024-05-11 16:21:09,631 : INFO : ConfigProcessor : Loading config from file c:\git\new folder (3)\mpf\mpf\mpfconfig.yaml.
2024-05-11 16:21:09,637 : INFO : ConfigProcessor : Loading config: c:\git\new folder (3)\mpf\mpf\mpfconfig.yaml
2024-05-11 16:21:09,637 : INFO : ConfigProcessor : Loading config from file C:\Users\octo\Downloads\homebrew\config\config.yaml.
2024-05-11 16:21:09,638 : INFO : ConfigProcessor : Loading config: C:\Users\octo\Downloads\homebrew\config\config.yaml
2024-05-11 16:21:09,638 : INFO : ConfigProcessor : Loading config: C:\Users\octo\Downloads\homebrew\config\lights.yaml
2024-05-11 16:21:09,639 : INFO : ConfigProcessor : Loading config: C:\Users\octo\Downloads\homebrew\config\coils.yaml
2024-05-11 16:21:09,640 : INFO : ConfigProcessor : Loading config: C:\Users\octo\Downloads\homebrew\config\switches.yaml
2024-05-11 16:21:09,640 : INFO : ConfigProcessor : Loading config: C:\Users\octo\Downloads\homebrew\config\sounds.yaml
2024-05-11 16:21:09,640 : WARNING : ConfigProcessor : Config section 'sounds' is deprecated in MPF 0.80 and will be ignored.
2024-05-11 16:21:09,641 : INFO : ConfigProcessor : Loading config: C:\Users\octo\Downloads\homebrew\config\images.yaml
2024-05-11 16:21:09,641 : INFO : ConfigProcessor : Loading config: C:\Users\octo\Downloads\homebrew\config\videos.yaml
2024-05-11 16:21:09,642 : INFO : ConfigProcessor : Config file cache created: C:\Users\octo\AppData\Local\Temp\1d0904511285da59b68333680e0b91d2.mpf_cache
2024-05-11 16:21:09,685 : INFO : ConfigProcessor : Loading config from cache: C:\Users\octo\AppData\Local\Temp\cd157f4be5c4430bfa418abc82c784ba.mpf_cache
2024-05-11 16:21:09,686 : INFO : ConfigProcessor : Loading config from cache: C:\Users\octo\AppData\Local\Temp\9a6ef7720776890324b2b6aefbdb5076.mpf_cache
2024-05-11 16:21:09,686 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\octo\Downloads\homebrew\modes\base\config\base.yaml
2024-05-11 16:21:09,686 : INFO : ConfigProcessor : Loading config from file C:\Users\octo\Downloads\homebrew\modes\base\config\base.yaml.
2024-05-11 16:21:09,687 : INFO : ConfigProcessor : Loading config: C:\Users\octo\Downloads\homebrew\modes\base\config\base.yaml
2024-05-11 16:21:09,687 : INFO : ConfigProcessor : Config file cache created: C:\Users\octo\AppData\Local\Temp\e87c946bbd0a2e05a931f281fca6458e.mpf_cache
2024-05-11 16:21:09,687 : INFO : ConfigProcessor : Loading config from cache: C:\Users\octo\AppData\Local\Temp\cd157f4be5c4430bfa418abc82c784ba.mpf_cache
2024-05-11 16:21:09,688 : INFO : ConfigProcessor : Loading config from cache: C:\Users\octo\AppData\Local\Temp\da852937ccb56145866cf54922bc01f8.mpf_cache
2024-05-11 16:21:09,688 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev1
2024-05-11 16:21:09,688 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2024-05-11-16-21-09-mpf-DESKTOP-BQT92E0.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2024-05-11 16:21:09,688 : INFO : Machine : MPF path: c:\git\new folder (3)\mpf\mpf
2024-05-11 16:21:09,688 : INFO : Machine : Machine path: C:\Users\octo\Downloads\homebrew
2024-05-11 16:21:09,688 : INFO : Machine : Platform: win32
2024-05-11 16:21:09,688 : INFO : Machine : Python executable location: C:\Users\octo\AppData\Local\Programs\Python\Python310\python.exe
2024-05-11 16:21:09,688 : INFO : Machine : Python version: 3.10.0 (64-bit)
2024-05-11 16:21:09,689 : INFO : Machine : Initializing MPF...
2024-05-11 16:21:09,789 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2024-05-11 16:21:09,797 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,797 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev1', 'prev_value': None, 'change': True}
2024-05-11 16:21:09,797 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev1, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2024-05-11 16:21:09,797 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.10.0', 'prev_value': None, 'change': True}
2024-05-11 16:21:09,803 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.19045-SP0', 'prev_value': None, 'change': True}
2024-05-11 16:21:09,803 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2024-05-11 16:21:09,803 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2024-05-11 16:21:09,803 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.19045', 'prev_value': None, 'change': True}
2024-05-11 16:21:09,803 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2024-05-11 16:21:09,803 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2024-05-11 16:21:09,811 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2024-05-11 16:21:09,813 : INFO : EventManager : Event: ======'bcp_connection_attempt'====== Args={'name': 'local_display', 'host': 'localhost', 'port': 5050}
2024-05-11 16:21:09,814 : INFO : BCPClientSocket : Connecting BCP to 'local_display' at localhost:5050...
2024-05-11 16:21:09,818 : INFO : BCPClientSocket : Connected BCP to 'local_display' localhost:5050
2024-05-11 16:21:09,819 : INFO : EventManager : Event: ======'bcp_clients_connected'====== Args={}
2024-05-11 16:21:09,887 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished name='Task-61' coro=<BallDevice._initialize_async() done, defined at c:\git\new folder (3)\mpf\mpf\devices\ball_device\ball_device.py:196> exception=ConfigFileError('Config validation error: Entry ball_device_counter_ball_switches:ball_device_counter_ball_switches:ball_switches = "s_trough_ball_1" is not valid. Device "s_trough_ball_1" not found in "switches:" section in your config.')>
Traceback (most recent call last):
  File "c:\git\new folder (3)\mpf\mpf\devices\ball_device\ball_device.py", line 198, in _initialize_async
    await self.ball_count_handler.initialize()
  File "c:\git\new folder (3)\mpf\mpf\devices\ball_device\ball_count_handler.py", line 92, in initialize
    self.counter = counter_class(self.ball_device, self.ball_device.config.get("counter", {}))
  File "c:\git\new folder (3)\mpf\mpf\devices\ball_device\switch_counter.py", line 27, in __init__
    self.config = self.machine.config_validator.validate_config("ball_device_counter_ball_switches", self.config)
  File "c:\git\new folder (3)\mpf\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "c:\git\new folder (3)\mpf\mpf\core\config_validator.py", line 204, in _validate_config
    processed_config[k] = self.validate_config_item(
  File "c:\git\new folder (3)\mpf\mpf\core\config_validator.py", line 256, in validate_config_item
    new_list.append(self.validate_item(i, validation, validation_failure_info))
  File "c:\git\new folder (3)\mpf\mpf\core\config_validator.py", line 696, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
  File "c:\git\new folder (3)\mpf\mpf\core\config_validator.py", line 410, in _validate_type_machine
    raise self.validation_error(item, validation_failure_info,
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry ball_device_counter_ball_switches:ball_device_counter_ball_switches:ball_switches = "s_trough_ball_1" is not valid. Device "s_trough_ball_1" not found in "switches:" section in your config. Error Code: CFE-ConfigValidator-6 (https://missionpinball.org/logs)
2024-05-11 16:21:09,888 : INFO : ball_device.bd_plunger : BCH: Initial count: 0
2024-05-11 16:21:09,888 : INFO : Machine : Starting the main run loop.
2024-05-11 16:21:09,888 : INFO : ball_device.bd_plunger : State: idle
2024-05-11 16:21:09,889 : INFO : Machine : Shutting down...
2024-05-11 16:21:09,889 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2024-05-11 16:21:09,893 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2024-05-11 16:21:09,894 : INFO : EventManager : Event: ======'init_phase_4'====== Args={}
2024-05-11 16:21:09,895 : ERROR : asyncio : Exception in callback Util.raise_exceptions(<Task finishe...unt_stable'")>) at c:\git\new folder (3)\mpf\mpf\core\utility_functions.py:790
handle: <Handle Util.raise_exceptions(<Task finishe...unt_stable'")>) at c:\git\new folder (3)\mpf\mpf\core\utility_functions.py:790>
Traceback (most recent call last):
  File "C:\Users\octo\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\git\new folder (3)\mpf\mpf\core\utility_functions.py", line 798, in raise_exceptions
    future.result()
  File "c:\git\new folder (3)\mpf\mpf\core\ball_controller.py", line 90, in _add_new_balls_to_playfield
    self.num_balls_known = await self._count_all_balls_in_devices()
  File "c:\git\new folder (3)\mpf\mpf\core\ball_controller.py", line 129, in _count_all_balls_in_devices
    futures.append(asyncio.ensure_future(device.ball_count_handler.counter.wait_for_count_stable()))
AttributeError: 'NoneType' object has no attribute 'wait_for_count_stable'
2024-05-11 16:21:09,895 : INFO : EventManager : Event: ======'machine_var_audits_events_game_ended'====== Args={'value': 0, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,896 : INFO : EventManager : Event: ======'machine_var_audits_events_game_started'====== Args={'value': 116, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,896 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_left_flipper'====== Args={'value': 90, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,896 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_left_flipper_eos'====== Args={'value': 90, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,896 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_left_inner_lane'====== Args={'value': 90, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,896 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_left_outer_lane'====== Args={'value': 90, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,896 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_left_sling'====== Args={'value': 90, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,896 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_plunger'====== Args={'value': 90, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,896 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_pop_bumper_1'====== Args={'value': 90, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,896 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_pop_bumper_2'====== Args={'value': 90, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,897 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_pop_bumper_3'====== Args={'value': 90, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,897 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_right_flipper'====== Args={'value': 90, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,897 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_right_flipper_eos'====== Args={'value': 90, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,897 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_right_inner_lane'====== Args={'value': 90, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,897 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_right_outer_lane'====== Args={'value': 90, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,897 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_right_sling'====== Args={'value': 90, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,897 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_start'====== Args={'value': 58, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,897 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_trough_ball_1'====== Args={'value': 90, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,897 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_trough_ball_2'====== Args={'value': 90, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,897 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_trough_ball_3'====== Args={'value': 90, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,898 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_trough_ball_4'====== Args={'value': 90, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,898 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_trough_ball_5'====== Args={'value': 90, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,898 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_trough_ball_6'====== Args={'value': 89, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,898 : INFO : EventManager : Event: ======'machine_var_audits_missing_switches_s_trough_ball_jam'====== Args={'value': 90, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,898 : INFO : EventManager : Event: ======'machine_var_audits_player_score'====== Args={'value': {'average': 0, 'top': [], 'total': 0}, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,898 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_auto_launcher'====== Args={'value': 0, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,898 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_ball_drain'====== Args={'value': 0, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,898 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_left_flipper'====== Args={'value': 36, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,898 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_left_flipper_eos'====== Args={'value': 0, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,898 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_left_inner_lane'====== Args={'value': 0, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,899 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_left_outer_lane'====== Args={'value': 0, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,899 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_left_sling'====== Args={'value': 7, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,899 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_plunger'====== Args={'value': 9, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,899 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_pop_bumper_1'====== Args={'value': 0, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,899 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_pop_bumper_2'====== Args={'value': 0, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,899 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_pop_bumper_3'====== Args={'value': 0, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,899 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_right_flipper'====== Args={'value': 131, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,899 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_right_flipper_eos'====== Args={'value': 0, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,899 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_right_inner_lane'====== Args={'value': 0, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,900 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_right_outer_lane'====== Args={'value': 0, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,901 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_right_sling'====== Args={'value': 3, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,901 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_start'====== Args={'value': 12, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,901 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_switch_2'====== Args={'value': 0, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,902 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough_ball_1'====== Args={'value': 4, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,902 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough_ball_2'====== Args={'value': 4, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,902 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough_ball_3'====== Args={'value': 1, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,902 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough_ball_4'====== Args={'value': 0, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,903 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough_ball_5'====== Args={'value': 0, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,903 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough_ball_6'====== Args={'value': 1, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,903 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough_ball_jam'====== Args={'value': 3, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,903 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_trough_eject_coil'====== Args={'value': 0, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,903 : INFO : EventManager : Event: ======'machine_var_audits_switches_s_mead'====== Args={'value': 0, 'prev_value': None, 'change': True}
2024-05-11 16:21:09,904 : INFO : EventManager : Event: ======'init_phase_5'====== Args={}
2024-05-11 16:21:09,904 : INFO : EventManager : Event: ======'init_done'====== Args={}
2024-05-11 16:21:09,904 : INFO : EventManager : Event: ======'machine_reset_phase_1'====== Args={}
2024-05-11 16:21:09,904 : INFO : EventManager : Event: ======'machine_reset_phase_2'====== Args={}
2024-05-11 16:21:09,904 : INFO : EventManager : Event: ======'machine_reset_phase_3'====== Args={}
2024-05-11 16:21:09,904 : INFO : EventManager : Event: ======'reset_complete'====== Args={}
2024-05-11 16:21:09,904 : INFO : EventManager : Event: ======'mode_attract_will_start'====== Args={}
2024-05-11 16:21:09,905 : INFO : EventManager : Event: ======'mode_attract_starting'====== Args={}
2024-05-11 16:21:09,905 : INFO : Mode.attract : Will not start because machine is shutting down.
2024-05-11 16:21:09,905 : ERROR : asyncio : Task was destroyed but it is pending!
task: <Task pending name='Task-79' coro=<IocpProactor.accept.<locals>.accept_coro() running at C:\Users\octo\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py:566> wait_for=<_OverlappedFuture cancelled>>
2024-05-11 16:21:09,905 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "c:\git\new folder (3)\mpf\mpf\core\machine.py", line 793, in _run_loop
    raise self._exception['exception']
  File "c:\git\new folder (3)\mpf\mpf\devices\ball_device\ball_device.py", line 198, in _initialize_async
    await self.ball_count_handler.initialize()
  File "c:\git\new folder (3)\mpf\mpf\devices\ball_device\ball_count_handler.py", line 92, in initialize
    self.counter = counter_class(self.ball_device, self.ball_device.config.get("counter", {}))
  File "c:\git\new folder (3)\mpf\mpf\devices\ball_device\switch_counter.py", line 27, in __init__
    self.config = self.machine.config_validator.validate_config("ball_device_counter_ball_switches", self.config)
  File "c:\git\new folder (3)\mpf\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "c:\git\new folder (3)\mpf\mpf\core\config_validator.py", line 204, in _validate_config
    processed_config[k] = self.validate_config_item(
  File "c:\git\new folder (3)\mpf\mpf\core\config_validator.py", line 256, in validate_config_item
    new_list.append(self.validate_item(i, validation, validation_failure_info))
  File "c:\git\new folder (3)\mpf\mpf\core\config_validator.py", line 696, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
  File "c:\git\new folder (3)\mpf\mpf\core\config_validator.py", line 410, in _validate_type_machine
    raise self.validation_error(item, validation_failure_info,
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry ball_device_counter_ball_switches:ball_device_counter_ball_switches:ball_switches = "s_trough_ball_1" is not valid. Device "s_trough_ball_1" not found in "switches:" section in your config. Error Code: CFE-ConfigValidator-6 (https://missionpinball.org/logs)
2024-05-11 16:22:00,750 : ERROR : root : 
Traceback (most recent call last):
  File "c:\git\new folder (3)\mpf\mpf\core\machine.py", line 793, in _run_loop
    raise self._exception['exception']
  File "c:\git\new folder (3)\mpf\mpf\devices\ball_device\ball_device.py", line 198, in _initialize_async
    await self.ball_count_handler.initialize()
  File "c:\git\new folder (3)\mpf\mpf\devices\ball_device\ball_count_handler.py", line 92, in initialize
    self.counter = counter_class(self.ball_device, self.ball_device.config.get("counter", {}))
  File "c:\git\new folder (3)\mpf\mpf\devices\ball_device\switch_counter.py", line 27, in __init__
    self.config = self.machine.config_validator.validate_config("ball_device_counter_ball_switches", self.config)
  File "c:\git\new folder (3)\mpf\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "c:\git\new folder (3)\mpf\mpf\core\config_validator.py", line 204, in _validate_config
    processed_config[k] = self.validate_config_item(
  File "c:\git\new folder (3)\mpf\mpf\core\config_validator.py", line 256, in validate_config_item
    new_list.append(self.validate_item(i, validation, validation_failure_info))
  File "c:\git\new folder (3)\mpf\mpf\core\config_validator.py", line 696, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
  File "c:\git\new folder (3)\mpf\mpf\core\config_validator.py", line 410, in _validate_type_machine
    raise self.validation_error(item, validation_failure_info,
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry ball_device_counter_ball_switches:ball_device_counter_ball_switches:ball_switches = "s_trough_ball_1" is not valid. Device "s_trough_ball_1" not found in "switches:" section in your config. Error Code: CFE-ConfigValidator-6 (https://missionpinball.org/logs)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\git\new folder (3)\mpf\mpf\commands\game.py", line 240, in __init__
    self.machine.run()
  File "c:\git\new folder (3)\mpf\mpf\core\machine.py", line 689, in run
    self._run_loop()
  File "c:\git\new folder (3)\mpf\mpf\core\machine.py", line 796, in _run_loop
    report_crash(self._exception['exception'], "exception_during_run", self.config)
  File "c:\git\new folder (3)\mpf\mpf\core\crash_reporter.py", line 236, in report_crash
    response = input("Do you want to report the crash to the MPF team (yes/no/show)? ")
EOFError
