2024-06-18 03:14:05,239 : INFO : root : Loading config.
2024-06-18 03:14:05,241 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-06-18 03:14:05,242 : INFO : ConfigProcessor : Loading config from cache: C:\Users\octo\AppData\Local\Temp\67114de119ffda0ef143dfc9c8b88aec.mpf_cache
2024-06-18 03:14:05,246 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\octo\Downloads\homebrew\config\lights.yaml
2024-06-18 03:14:05,246 : INFO : ConfigProcessor : Loading config from file c:\git\new folder (6)\mpf\mpf\mpfconfig.yaml.
2024-06-18 03:14:05,251 : INFO : ConfigProcessor : Loading config: c:\git\new folder (6)\mpf\mpf\mpfconfig.yaml
2024-06-18 03:14:05,251 : INFO : ConfigProcessor : Loading config from file C:\Users\octo\Downloads\homebrew\config\config.yaml.
2024-06-18 03:14:05,252 : INFO : ConfigProcessor : Loading config: C:\Users\octo\Downloads\homebrew\config\config.yaml
2024-06-18 03:14:05,253 : INFO : ConfigProcessor : Loading config: C:\Users\octo\Downloads\homebrew\config\lights.yaml
2024-06-18 03:14:05,253 : INFO : ConfigProcessor : Loading config: C:\Users\octo\Downloads\homebrew\config\coils.yaml
2024-06-18 03:14:05,254 : INFO : ConfigProcessor : Loading config: C:\Users\octo\Downloads\homebrew\config\switches.yaml
2024-06-18 03:14:05,255 : INFO : ConfigProcessor : Loading config: C:\Users\octo\Downloads\homebrew\config\sounds.yaml
2024-06-18 03:14:05,255 : WARNING : ConfigProcessor : Config section 'sounds' is deprecated in MPF 0.80 and will be ignored.
2024-06-18 03:14:05,255 : INFO : ConfigProcessor : Loading config: C:\Users\octo\Downloads\homebrew\config\images.yaml
2024-06-18 03:14:05,255 : INFO : ConfigProcessor : Loading config: C:\Users\octo\Downloads\homebrew\config\videos.yaml
2024-06-18 03:14:05,256 : INFO : ConfigProcessor : Config file cache created: C:\Users\octo\AppData\Local\Temp\67114de119ffda0ef143dfc9c8b88aec.mpf_cache
2024-06-18 03:14:05,295 : INFO : ConfigProcessor : Loading config from cache: C:\Users\octo\AppData\Local\Temp\d4fb548c2902111733185c907c7e02f2.mpf_cache
2024-06-18 03:14:05,295 : INFO : ConfigProcessor : Loading config from cache: C:\Users\octo\AppData\Local\Temp\5cdf3f6f669e12795623fbd605d1b6a0.mpf_cache
2024-06-18 03:14:05,295 : INFO : ConfigProcessor : Loading config from cache: C:\Users\octo\AppData\Local\Temp\e87c946bbd0a2e05a931f281fca6458e.mpf_cache
2024-06-18 03:14:05,296 : INFO : ConfigProcessor : Loading config from cache: C:\Users\octo\AppData\Local\Temp\d4fb548c2902111733185c907c7e02f2.mpf_cache
2024-06-18 03:14:05,296 : INFO : ConfigProcessor : Loading config from cache: C:\Users\octo\AppData\Local\Temp\da852937ccb56145866cf54922bc01f8.mpf_cache
2024-06-18 03:14:05,297 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev1
2024-06-18 03:14:05,297 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2024-06-18-03-14-05-mpf-DESKTOP-BQT92E0.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2024-06-18 03:14:05,297 : INFO : Machine : MPF path: c:\git\new folder (6)\mpf\mpf
2024-06-18 03:14:05,297 : INFO : Machine : Machine path: C:\Users\octo\Downloads\homebrew
2024-06-18 03:14:05,297 : INFO : Machine : Platform: win32
2024-06-18 03:14:05,297 : INFO : Machine : Python executable location: C:\Users\octo\AppData\Local\Programs\Python\Python310\python.exe
2024-06-18 03:14:05,297 : INFO : Machine : Python version: 3.10.0 (64-bit)
2024-06-18 03:14:05,298 : INFO : Machine : Initializing MPF...
2024-06-18 03:14:05,394 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2024-06-18 03:14:05,402 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2024-06-18 03:14:05,402 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev1', 'prev_value': None, 'change': True}
2024-06-18 03:14:05,402 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev1, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2024-06-18 03:14:05,402 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.10.0', 'prev_value': None, 'change': True}
2024-06-18 03:14:05,407 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-10-10.0.19045-SP0', 'prev_value': None, 'change': True}
2024-06-18 03:14:05,407 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2024-06-18 03:14:05,407 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '10', 'prev_value': None, 'change': True}
2024-06-18 03:14:05,407 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.19045', 'prev_value': None, 'change': True}
2024-06-18 03:14:05,407 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2024-06-18 03:14:05,407 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2024-06-18 03:14:05,416 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2024-06-18 03:14:05,416 : INFO : SwitchController : Found active switch: ('3208-8', <Platform.Virtual>) <switch.s_trough_ball_2>
2024-06-18 03:14:05,416 : INFO : SwitchController : Found active switch: ('3208-9', <Platform.Virtual>) <switch.s_trough_ball_3>
2024-06-18 03:14:05,416 : INFO : SwitchController : Found active switch: ('3208-13', <Platform.Virtual>) <switch.s_trough_ball_1>
2024-06-18 03:14:05,418 : ERROR : ConfigValidator : Your config contains a value for the setting "widget_player:expires", but this is not a valid setting name.
2024-06-18 03:14:05,418 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe...tting name.')>)
handle: <Handle EventManager._queue_task_done(<Task finishe...tting name.')>)>
Traceback (most recent call last):
  File "C:\Users\octo\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\git\new folder (6)\mpf\mpf\core\events.py", line 795, in _queue_task_done
    future.result()
  File "c:\git\new folder (6)\mpf\mpf\core\events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "c:\git\new folder (6)\mpf\mpf\core\mode_controller.py", line 97, in initialize_modes
    item.method(config=mode.config[item.config_section],
  File "c:\git\new folder (6)\mpf\mpf\core\config_player.py", line 150, in process_mode_config
    config = self.validate_config(config)
  File "c:\git\new folder (6)\mpf\mpf\core\config_player.py", line 113, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
  File "c:\git\new folder (6)\mpf\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "c:\git\new folder (6)\mpf\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
  File "c:\git\new folder (6)\mpf\mpf\config_players\widget_player.py", line 18, in _validate_config_item
    device_settings = self.machine.config_validator.validate_config(
  File "c:\git\new folder (6)\mpf\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "c:\git\new folder (6)\mpf\mpf\core\config_validator.py", line 177, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "c:\git\new folder (6)\mpf\mpf\core\config_validator.py", line 345, in check_for_invalid_sections
    raise ConfigFileError('Your config contains a value for the '
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Failed to load config player mode_attract_started:widgets with settings {'high_score': {'target': 'mini_screen', 'expires': '10s'}} >> Your config contains a value for the setting "widget_player:expires", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://missionpinball.org/logs)
2024-06-18 03:14:05,445 : INFO : Machine : Starting the main run loop.
2024-06-18 03:14:05,447 : INFO : Machine : Shutting down...
2024-06-18 03:14:05,447 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2024-06-18 03:14:06,467 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "c:\git\new folder (6)\mpf\mpf\core\machine.py", line 793, in _run_loop
    raise self._exception['exception']
  File "C:\Users\octo\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "c:\git\new folder (6)\mpf\mpf\core\events.py", line 795, in _queue_task_done
    future.result()
  File "c:\git\new folder (6)\mpf\mpf\core\events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "c:\git\new folder (6)\mpf\mpf\core\mode_controller.py", line 97, in initialize_modes
    item.method(config=mode.config[item.config_section],
  File "c:\git\new folder (6)\mpf\mpf\core\config_player.py", line 150, in process_mode_config
    config = self.validate_config(config)
  File "c:\git\new folder (6)\mpf\mpf\core\config_player.py", line 113, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
  File "c:\git\new folder (6)\mpf\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "c:\git\new folder (6)\mpf\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
  File "c:\git\new folder (6)\mpf\mpf\config_players\widget_player.py", line 18, in _validate_config_item
    device_settings = self.machine.config_validator.validate_config(
  File "c:\git\new folder (6)\mpf\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
  File "c:\git\new folder (6)\mpf\mpf\core\config_validator.py", line 177, in _validate_config
    self.check_for_invalid_sections(this_spec, source, validation_failure_info)
  File "c:\git\new folder (6)\mpf\mpf\core\config_validator.py", line 345, in check_for_invalid_sections
    raise ConfigFileError('Your config contains a value for the '
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Failed to load config player mode_attract_started:widgets with settings {'high_score': {'target': 'mini_screen', 'expires': '10s'}} >> Your config contains a value for the setting "widget_player:expires", but this is not a valid setting name. Error Code: CFE-ConfigValidator-2 (https://missionpinball.org/logs)
2024-06-18 03:14:19,366 : INFO : root : MPF run loop ended.
